### ISSUE TITLE
autocompletion and [TAB] action does not work on linux

### ISSUE THREAD

**Issue by mherkazandjian** [ionelmc/python-remote-pdb#15]
Hi,

I started using remote-pdb a few days ago and i noticed that the [TAB] action does not work under
linux. I am not sure if this is the case on other OSes too.
After telnet'ing when i press [TAB] the cursor just moves forward with a tab space.

i think it would be really cool if the TAB completion works via telnet.

i hope this will be takes into account and implemented, i'll be happy to contribute with some of my time in case i can be helpful.

Best,

**Comment by ionelmc** [comment]
This project will never have such a feature. The goal is to have something really simple that doesn't break all the time. There are other remote debuggers with tab-completion, check out twisted's manhole and such.

The only thing we can change here is to add a list of links to the more fancy stuff in the readme.

**Comment by mherkazandjian** [comment]
ok no problem if tab completion seems problematic.
i usually use pydev, but i like this project bec it is lightweight, so maybe better keep it that way.
i'll try twisted's manhole, any other remote debuggers that i could try?

**Comment by ionelmc** [comment]
https://wiki.python.org/moin/PythonDebuggingTools is a good start

**Comment by mherkazandjian** [comment]
ok tnx.

**Comment by chaoflow** [comment]
@ionelmc [pdbpp](https://github.com/pdbpp/pdbpp) is a drop-in replacement for pdb supporting tab completion. Having it installed alongside remote-pdb, I see the ``(Pdb++)`` prompt, connecting via ``socat readline ...``. Tab completion however is completing files in the current directory, same as if pdbpp is not installed.

Could the combination with pdbpp be an approach to get tab completion within remote-pdb?

**Comment by ionelmc** [comment]
Nope. pdbpp expects a tty/pty which this project doesn't provide by design.
