### ISSUE TITLE
Question: PyCharm Debugging with Remote-Pdb?

### ISSUE THREAD

**Issue by MarkDHarris** [ionelmc/python-remote-pdb#16]
Is it possible to attach the PyCharm debugger to a process waiting after executing "RemotePdb("0.0.0.0", 5005).set_trace()"?

If so, how?  I have tried every combination of remote, local, attach, run/debug config and anything else that I can find in the PyCharm UI but nothing seems cause it to connect.  What is the PyCharm equivilent of "nc -C 127.0.0.1 5005"?

**Comment by ionelmc** [comment]
If it's on the same host you can use "Attach to Process". For remote hosts see https://www.jetbrains.com/help/pycharm/remote-debugging-with-product.html

I made this project with a very simple and small goal in mind. Interoperating with other debuggers not included in said goal.
