### ISSUE TITLE
Silent / quiet mode

### ISSUE THREAD

**Issue by asottile** [ionelmc/python-remote-pdb#17]
cool tool!

I'm playing around with `curses` right now and a remote debugger is exceptionally good for this -- the one thing that's a bit unfortunate is `remote-pdb` will always print output breaking the curses output:

![](https://i.fluffy.cc/m6H3wxwxgxSZm5kg20ld3xphkFcZK3T5.png)

would you accept a PR which allows an option (and environment variable) to silence this?

**Comment by ionelmc** [comment]
Oooof ... looks like there's a print in addition to logging.critical. I guess there could be an env var or an extra option to RemotePdb.__init__ ...

Btw, did you know you can use pudb remotely? https://documen.tician.de/pudb/starting.html#debugging-from-a-separate-terminal (2 ways: tty or tcp)

**Comment by asottile** [comment]
yeah I've used `pudb` before -- this is just way simpler :D -- I might send a few patches your way ;)
