### ISSUE TITLE
Source code gets chopped off in a remote session

### ISSUE THREAD

**Issue by TheMeaningfulEngineer** [ionelmc/python-remote-pdb#21]
I'm using this module together with [pdbpp](https://github.com/pdbpp/pdbpp). This promises to offer the `sticky` option of pdbpp also for remote sessions. 

One problem however seems to be that the terminal size is for some reason fixed and this results in not all the code being shown.

I'm posting this here just to start the conversation, it if possible this might be a pdbpp issue.

**Comment by ionelmc** [comment]
Afaik pdb++ expects a tty. Remote-pdb's goal is to avoid implementing a full telnet protocol to support ttys.

**Comment by TheMeaningfulEngineer** [comment]
Thanks for the clarification. 
This seems solved than
