### ISSUE TITLE
pdbpp

### ISSUE THREAD

**Issue by synic** [ionelmc/python-remote-pdb#23]
`pdbpp==0.10.2`
`remote-pdb==2.0.0`
`Python==3.8.0`

The strangest thing. If I install pdbpp and remote-pdb, the first remote debugging session does not use pdbpp. Subsquent sessions it works.

What could be going wrong here?

**Comment by synic** [comment]
Nevermind, this is my problem.

**Comment by ionelmc** [comment]
It's not supposed to work anyway ... pdbpp expects a terminal.
