### ISSUE TITLE
Jython Support

### ISSUE THREAD

**Issue by rripken** [ionelmc/python-remote-pdb#25]
Could the project description include a brief statement about whether or not the debugger should function under Jython 2.7.2 ?  I see Python 2.7 badge but I know Jython is a bit weird.

**Comment by ionelmc** [comment]
I wouldn't state anything without any testing. In theory it should work. Why do you care about this if you haven't tried it on jython?

**Comment by rripken** [comment]
I did some brief testing and python-remote-pdb appears to work with my application in Jython.
