### ISSUE TITLE
Connection in Docker drops immediately

### ISSUE THREAD

**Issue by scossu** [ionelmc/python-remote-pdb#26]
I just started using remote-pdb and run into an issue. If I run the debugger inside a running Docker container I am not able to establish a persistent connection with the debugger from the host. If I start a shell inside the docker container  and run `nc -vv localhost 4444` I obtain the expected prompt: 

```
localhost (127.0.0.1:4444) open
> [My code breakpoint info]
(Pdb) 
```
But if I run the same from the host, the connection is terminated immediately: 

```
$ nc -vv localhost 4444
Notice: Real hostname for localhost [127.0.0.1] is workbox1
localhost [127.0.0.1] 4444 (krb524) open
Total received bytes: 0
Total sent bytes: 0
```

I'm mapping host port 4444 to guest:4444, and I tried other mappings to ensure that was not the problem, but I get the same result consistently.

I am using Python 3.7's `breakpoint()` command. I have the following env variables read by Docker: 

```
PYTHONBREAKPOINT=remote_pdb.set_trace
REMOTE_PDB_HOST=127.0.0.1
REMOTE_PDB_PORT=4444
```
My host is Arch linux (GNU netcat 0.7.1) and the guest is Alpine (nc  part of Busybox 1.30.1). I can  reproduce the same issue with socat and telnet.

This is an increedibly useful tool and if I could use it from the host it would be so much more efficient. Any help is appreciated.

**Comment by scossu** [comment]
After some more testing, I figured out that setting

```
REMOTE_PDB_HOST=0.0.0.0
```

fixed the issue. 

I may suggest that adding a small note to the README in regard may save distracted people like me some troubleshooting.

**Comment by ionelmc** [comment]
I'll add a note, sure.
