### ISSUE TITLE
set_trace call vs RemotePdb instance

### ISSUE THREAD

**Issue by chrisamow** [ionelmc/python-remote-pdb#29]
Hi,
I was looking at doing a similar change as a PR for pudb and was looking at your source.

Going by your usage instructions - is there any reason to use the RemotePdb class when calling set_trace() with the same parameters seems to take care of that for you?

Thanks!

**Comment by ionelmc** [comment]
Not really. The class interface is there in case you want to subclass it or pass it to something that expects a Pdb-like class object.

**Comment by chrisamow** [comment]
Thanks, have a good one
