### ISSUE TITLE
Pdb doesn't stop on set_trace command.

### ISSUE THREAD

**Issue by kkujawinski** [ionelmc/python-remote-pdb#4]
When connected to remote pdb few commands after ```set_trace``` call are executed. In following code pdb would stop around ```x=3```.

```
def test():
    import remote_pdb; rp = remote_pdb.RemotePdb(host='0.0.0.0', port=4444); rp.set_trace()
    return {}

test()
x = 3
```

**Comment by ionelmc** [comment]
Should be fixed by https://github.com/ionelmc/python-remote-pdb/commit/5665a0d8486ebc2e3a58a33fb15a1cadf5e2f71e
